name: yjeek_driver
description: Yjeek Driver App - delivery driver mobile application.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  image_picker_android: ^0.8.13+19
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.14.0
  google_maps_flutter_platform_interface: ^2.9.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
