// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEa3x1Yu5g9gHOnU8ohgNkGkSDHFl5c20',
    appId: '1:345308459087:android:077e74313e7af1baf83a3a',
    messagingSenderId: '345308459087',
    projectId: 'delivery-app-frontend-key',
    storageBucket: 'delivery-app-frontend-key.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7YtvFJCwm7juGsY1hAONd8Ubqdcgyx8',
    appId: '1:345308459087:ios:c83144cfce8af756f83a3a',
    messagingSenderId: '345308459087',
    projectId: 'delivery-app-frontend-key',
    storageBucket: 'delivery-app-frontend-key.firebasestorage.app',
    iosClientId:
        '345308459087-05t0d0dbcql135tiqq4of5ug5rojdps1.apps.googleusercontent.com',
    iosBundleId: 'bh.yjeek.driver',
  );
}
